org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.21.12)
java_version=21

neo_version=21.11.32-beta
neo_version_range=[21.11.0-beta,22)
loader_version_range=[4,)
ftb_library_version=2111.1.1
ftb_library_version_range=[2111.1.1,2112)
ftb_essentials_version=2111.1.1
ftb_essentials_version_range=[2111.1.1,2112)

mod_id=paper_plane
mod_name=Paper Plane
mod_license=GPL-3.0-only
mod_version=1.0.0
mod_group_id=dev.rinchan
mod_authors=RinChan
mod_description=Paper planes for player-to-player teleport requests.

fabric_loader_version=0.18.4
fabric_api_version=0.140.2+1.21.11
