org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
java_version=25

neo_version=26.1.2.71
neo_version_range=[21.1.0,)
loader_version_range=[4,)
ftb_library_version=26.1.2.7
ftb_library_version_range=[26.1.1.1,27)
ftb_essentials_version=26.1.2.4
ftb_essentials_version_range=[26.1.2.1,27)
lychee_version=6byc5OgT
lychee_version_range=[26,27)
kiwi_version=5Vq6yLfN
kiwi_version_range=[26,27)

mod_id=paper_plane
mod_name=Paper Plane
mod_license=GPL-3.0-only
mod_version=1.0.0
mod_group_id=dev.rinchan
mod_authors=RinChan
mod_description=Paper planes for player-to-player teleport requests.

# Fabric 1.21.1
fabric_loader_version=0.19.2
fabric_api_version=0.155.2+26.1.2
ftb_library_fabric_version=26.1.2.7
ftb_essentials_fabric_version=26.1.2.4
lychee_fabric_version=JiKCXnFv
kiwi_fabric_version=LGotkvzL
architectury_fabric_version=hNxqF6r7
