plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.145'
    id 'maven-publish'
}

base {
    archivesName = "${rootProject.mod_id}-neoforge"
}

sourceSets {
    main {
        java.srcDir rootProject.file('common/src/main/java')
        resources.srcDir rootProject.file('common/src/main/resources')
    }
    test.java.srcDir rootProject.file('common/src/test/java')
}

dependencies {
    implementation "net.neoforged:neoforge:${rootProject.neo_version}"
    implementation("dev.ftb.mods:ftb-library-forge:${rootProject.ftb_library_version}") { transitive = false }
    implementation("dev.ftb.mods:ftb-essentials-forge:${rootProject.ftb_essentials_version}") { transitive = false }
    implementation("dev.architectury:architectury-forge:11.1.17") { transitive = false }
    annotationProcessor "io.github.llamalad7:mixinextras-common:${rootProject.mixin_extras_version}"
    implementation "io.github.llamalad7:mixinextras-neoforge:${rootProject.mixin_extras_version}"
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
        minecraft_version_range: minecraft_version_range,
        neo_version_range: neo_version_range,
        loader_version_range: loader_version_range,
        mod_id: mod_id,
        mod_name: mod_name,
        mod_license: mod_license,
        mod_version: mod_version,
        mod_authors: mod_authors,
        mod_description: mod_description,
        ftb_library_version_range: ftb_library_version_range,
        ftb_essentials_version_range: ftb_essentials_version_range
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into layout.buildDirectory.dir('generated/sources/modMetadata')
}

sourceSets.main.resources.srcDir generateModMetadata

jar {
    manifest.attributes('MixinConfigs': 'paper_plane.mixins.json')
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${base.archivesName.get()}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "${rootProject.mod_id}-neoforge"
            from components.java
        }
    }
}
